project_id = "zbxgsogsiscxxefkucqk"

[functions.create-pix-payment]
verify_jwt = false

[functions.check-pix-status]
verify_jwt = false

[functions.sigilopay-webhook]
verify_jwt = false

[functions.update-checkout-status]
verify_jwt = false

[functions.generate-ninja-coupon]
verify_jwt = false

[functions.validate-ninja-coupon]
verify_jwt = false
